version: '2.3'
services:
  python:
    container_name: 'python'
    build:
      context: ..
      dockerfile: "python-docker/Dockerfile"
    user: root
    tty: true
    volumes:
      - ../:/workplace
    ports:
      - "8889:8889"
    runtime: nvidia 
    environment:
      TZ: Asia/Tokyo
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    working_dir: /workplace
