version: '3'
services:
  python:
    container_name: 'python.cpu'
    image: akitenkrad/python.cpu.arm64:latest
    user: root
    tty: true
    volumes:
      - ./:/workplace:cached
    environment:
      TZ: Asia/Tokyo
    working_dir: /workplace
