version: '2.3'
services:
  python:
    container_name: 'python.gpu'
    image: akitenkrad/python.gpu:latest
    platform: linux/amd64 # for Apple Mac M1
    user: root
    tty: true
    volumes:
      - ./:/workplace:cached
    runtime: nvidia 
    environment:
      TZ: Asia/Tokyo
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    working_dir: /workplace
